# Generated by Django 5.1.4 on 2024-12-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Athletes",
            fields=[
                ("code", models.IntegerField(primary_key=True, serialize=False)),
                ("current", models.BooleanField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_short", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("function", models.CharField(blank=True, max_length=50, null=True)),
                ("country_code", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "country_long",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nationality_long",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nationality_code",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("disciplines", models.TextField(blank=True, null=True)),
                ("events", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "birth_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "residence_place",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "residence_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("hobbies", models.TextField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=50, null=True)),
                ("education", models.TextField(blank=True, null=True)),
                ("lang", models.CharField(blank=True, max_length=100, null=True)),
                ("coach", models.TextField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("influence", models.TextField(blank=True, null=True)),
                ("philosophy", models.TextField(blank=True, null=True)),
                ("event_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "athletes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                ("event_id", models.IntegerField(primary_key=True, serialize=False)),
                ("event", models.CharField(blank=True, max_length=100, null=True)),
                ("tag", models.CharField(blank=True, max_length=50, null=True)),
                ("sport", models.CharField(blank=True, max_length=50, null=True)),
                ("sport_code", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                "db_table": "events",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Medallists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medal_date", models.DateField(blank=True, null=True)),
                ("medal_type", models.CharField(blank=True, max_length=20, null=True)),
                ("medal_code", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("country_code", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "country_long",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nationality_code",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "nationality_long",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("team", models.CharField(blank=True, max_length=100, null=True)),
                ("discipline", models.CharField(blank=True, max_length=50, null=True)),
                ("event", models.CharField(blank=True, max_length=100, null=True)),
                ("event_type", models.CharField(blank=True, max_length=10, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "code_athlete",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("code_team", models.CharField(blank=True, max_length=30, null=True)),
                ("is_medallist", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "medallists",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Medals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medal_type", models.CharField(blank=True, max_length=20, null=True)),
                ("medal_code", models.IntegerField(blank=True, null=True)),
                ("medal_date", models.DateField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("gender", models.CharField(blank=True, max_length=1, null=True)),
                ("discipline", models.CharField(blank=True, max_length=50, null=True)),
                ("event", models.CharField(blank=True, max_length=100, null=True)),
                ("event_type", models.CharField(blank=True, max_length=10, null=True)),
                ("code", models.CharField(blank=True, max_length=30, null=True)),
                ("country_code", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "country_long",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "medals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Schedules",
            fields=[
                ("schedule_id", models.CharField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("day", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("discipline", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "discipline_code",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("event", models.CharField(blank=True, max_length=50, null=True)),
                ("event_medal", models.IntegerField(blank=True, null=True)),
                ("phase", models.CharField(blank=True, max_length=100, null=True)),
                ("gender", models.CharField(blank=True, max_length=1, null=True)),
                ("event_type", models.CharField(blank=True, max_length=20, null=True)),
                ("venue", models.CharField(blank=True, max_length=100, null=True)),
                ("venue_code", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "location_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_code",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("event_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "schedules",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                ("current", models.BooleanField(blank=True, null=True)),
                ("team", models.CharField(blank=True, max_length=100, null=True)),
                ("country_code", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "country_long",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("discipline", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "disciplines_code",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("events", models.CharField(blank=True, max_length=50, null=True)),
                ("athletes", models.TextField(blank=True, null=True)),
                ("athletes_codes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "teams",
                "managed": False,
            },
        ),
    ]
